name: Sourcegraph Go LSIF Indexer
description: Generate LSIF data from Go source code
author: Sourcegraph
branding:
  icon: code
  color: purple

inputs:
  file:
    description: The output filename (relative to the repository root).
    default: dump.lsif
  project_root: 
    description: The root of the repository.
    default: .
  module_root:
    description: The directory where go.mod is located (relative to the repository).
    default: .
  additional_args:
    description: These arguments are passed directly to lsif-go.
    default: ''

runs:
  using: docker
  image: Dockerfile
  env:
    OUT: ${{ inputs.file }}
    PROJECT_ROOT: ${{ inputs.project_root }}
    MODULE_ROOT: ${{ inputs.module_root }}
    ADDITIONAL_ARGS: ${{ intputs.additional_args }}
